# Generated by Django 4.1.6 on 2023-02-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='file_id',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='region_id',
            new_name='region',
        ),
    ]
