# Generated by Django 4.1.6 on 2023-03-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
