# Generated by Django 4.1.6 on 2023-03-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_clientrequest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachposts',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
