# Generated by Django 4.1.6 on 2023-03-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_coaches_email_students_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaches',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
    ]
